name: Build & Push Docker Image

on:
  push:
    branches: [ "DebmalyaPan" ]
  pull_request:
    branches: [ "DebmalyaPan" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      # Build Spring Boot JAR
      - name: Build with Maven (skip tests)
        working-directory: Ride-Sharing
        run: mvn -B package -DskipTests

      # Build & Push Docker Image using mr-smithers-excellent
      - name: Build & Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: debmalya06/ride-sharing-app
          tags: latest
          registry: docker.io
          dockerfile: Ride-Sharing/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Trigger render deploy
      - name: Trigger Render Deploy
        run: curl -X POST "${{ secrets.HOOK_URL }}"
  